### ISSUE TITLE
SEIRD Simulator in Python

### ISSUE THREAD

**Issue by pinkfloydisch** [silpara/simulators#1]
Hi, 
Thanks a lot for very nice, clean and useful code. surprisingly it is exactly the mode which I am working on it. I am studying mathematics and it is very important for me to estimate the parameters, especially beta, 
May I ask you to write additional code for SEIRD model regarding the least square error and minimizing it which leads to estimate the parameters. I am working on it but I have problem in coding part of it. the problem that I have is that maybe separately I or D are fitted to the data but all together usually no. my first guess for beta is something between 0.5 to 1 ,  sigma 1 / 5.6 , gamma = 1/14 and mu = 0.02

the problem is that it is difficult for me how to write a code which I can use real data of infected and death people (even recovered)  at the same time into my code to minimize the least square in several aspects and estimate the parameters better.

Sorry for the long message. I thought maybe you can help me.
have a nice and safe days
Best regards,
Nik

**Comment by silpara** [comment]
Hi Nik,

It was in the plan. Have published a post: [Estimating Parameters of Compartmental Models from Observed Data](https://towardsdatascience.com/estimating-parameters-of-compartmental-models-from-observed-data-62f87966bb2b)

Here are the notebooks demonstrating the parameter estimation
[Simulation & Parameter Estimation of SEIR Model](https://github.com/silpara/simulators/blob/master/compartmental_models/SEIR%20Simulator%20with%20Parameter%20Estimation%20in%20Python.ipynb)
[Simulation & Parameter Estimation of SEIRD Model](https://github.com/silpara/simulators/blob/master/compartmental_models/SEIRD%20Simulator%20with%20Parameter%20Estimation%20in%20Python.ipynb)

I have no background in medicine or epidemiology, neither this code has been vetted by any expert, so be careful for what purpose you use it. Ask experts to you know to validate the results if you are planning to use them one way or the other.

Cheers,
Abhay
